import type { ComponentMetadata } from "./types"

const subComponentsMap: Record<string, string[]> = {
  TextInput: ["Label", "HelperText", "Icon"],
  SearchInput: ["TextInput", "Spinner"],
  PhoneInput: ["TextInput", "Dropdown"],
  Command: ["SearchInput", "Spinner", "Icon"],
  Calendar: ["Button", "Text"],
  DatePicker: ["TextInput", "Calendar"],
  TimePicker: ["TextInput"],
  DateRangePicker: ["TextInput", "Calendar", "Button"],
  Upload: ["Button", "Text", "Image", "Spinner"],
  Textarea: ["Label", "HelperText"],
  Checkbox: ["Text", "HelperText"],
  Radio: ["Text", "HelperText"],
  Toggle: ["Text", "HelperText"],
  Slider: ["Label", "HelperText"],
  Label: ["Text"],
  HelperText: ["Text"],
  Button: ["Icon", "Spinner"],
  FAB: ["Icon"],
  Card: [],
  Separator: [],
  Text: ["Icon"],
  Spinner: ["Text"],
  Skeleton: [],
  PillGroup: ["Pill", "Spinner"],
  Pill: ["Text", "Spinner"],
  Avatar: ["Icon"],
  AvatarGroup: ["Avatar"],
  Progress: ["Text"],
  Kbd: [],
  Image: ["Skeleton"],
  Icon: [],
  VisuallyHidden: [],
  ErrorBoundary: ["Text"],
  Link: [],
  Stack: [],
  Grid: [],
  AspectRatio: [],
  Rating: ["Text"],
  DescriptionList: [],
  InputOTP: [],
  List: ["Stack", "Grid", "SearchInput", "Text", "Icon"],
  Video: [],
  Overlay: [],
  Modal: ["Overlay", "Card", "Button"],
  AlertDialog: ["Overlay", "Text", "Button"],
  Drawer: ["Overlay", "Card", "Button"],
  Popover: ["Card", "Button"],
  HoverCard: ["Popover"],
  Toast: ["Text", "Button", "Icon"],
  Toaster: ["Toast"],
  Form: ["FormField", "Button"],
  FormField: ["Label", "HelperText", "TextInput"],
  Tooltip: [],
  ResizablePanelGroup: ["ResizablePanel", "ResizableHandle"],
  ResizablePanel: [],
  ResizableHandle: [],
  Breadcrumb: ["Link", "Text"],
  Pagination: ["Button", "Text"],
  Select: ["Label", "HelperText", "Icon"],
  Tabs: ["Text", "Icon", "Button"],
  Dropdown: ["Button", "Icon"],
  Navbar: ["Button", "Link", "Dropdown", "Separator"],
  Sidebar: ["Button", "Link", "Text", "Separator", "Collapsible"],
  NavigationMenu: ["Button", "Link", "Text", "Icon", "Popover"],
  Menubar: ["Button", "Dropdown"],
  ContextMenu: ["Dropdown", "Icon"],
  Stepper: ["Button", "Text", "Icon"],
  Table: ["Checkbox", "Button", "Text", "Skeleton", "Pagination", "EmptyState"],
  CodeBlock: ["CopyButton", "Text"],
  CopyButton: ["Button", "Tooltip"],
  SplitButton: ["Button", "Dropdown"],
  RadioGroup: ["Radio"],
  InputGroup: ["InputGroupInput", "InputGroupAddon", "InputGroupButton", "Button"],
  Collapsible: ["Button"],
  Accordion: ["Collapsible", "Spinner", "Icon"],
  Alert: ["Text", "Button", "Icon"],
  LoadingOverlay: ["Overlay", "Spinner"],
  EmptyState: ["Text", "Button", "Icon"],
  PageHeader: ["Text", "Pill", "Separator", "Icon"],
  PageFooter: ["Text", "Separator"],
  Hero: ["Text", "Button", "Image", "Pill"],
  AuthLayout: ["Card", "Text"],
  AppShell: ["Sidebar", "Navbar", "PageFooter"],
  HistoryControlButtons: ["Button", "Tooltip"],
  FixedScreenWidget: ["Button", "Card"],
  InlineEdit: ["TextInput", "Text", "Button"],
  TreeView: ["Text", "Icon", "Spinner"],
  Carousel: ["Image", "Button", "Text"],
  Chart: [],
  BarChart: ["Chart"],
  LineChart: ["Chart"],
  PieChart: ["Chart"],
  ResizeContainer: ["ResizablePanelGroup", "ResizablePanel", "ResizableHandle"],
  TriggerModal: ["Modal", "Button"],
  ConfirmModal: ["TriggerModal", "PageHeader", "Button", "Icon"],
  FormModal: ["TriggerModal", "Form", "FormField", "PageHeader", "Button", "Icon"],
  // FieldLayout: ["Label", "HelperText"],
}



export function getSubComponents(componentName: string): string[] {
  return subComponentsMap[componentName] || []
}

export function getAllSubComponents(): string[] {
  const allSubComponents = new Set<string>()
  Object.values(subComponentsMap).forEach((subs) => {
    subs.forEach((sub) => allSubComponents.add(sub))
  })
  return Array.from(allSubComponents).sort()
}
